name: sembast_web_html_compat
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  idb_shim: '>=2.5.0 <4.0.0'
  sembast:
  sembast_web:
  sembast_test:
    git:
      url: https://github.com/tekartik/sembast.dart
      path: sembast_test
      ref: dart3a
  idb_shim_html_compat:
    git:
      url: https://github.com/tekartik/idb_shim_more.dart
      path: packages/idb_shim_html_compat
      ref: dart3a
    version: '>=0.3.3'

dev_dependencies:
  lints: '>=4.0.0'
  test: '>=1.24.0'
resolution: workspace
