name: tekartik_idb_provider
version: 0.4.0
description: Provider pattern on top of indexeddb
publish_to: none
environment:
  sdk: ^3.6.0
dependencies:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
  idb_shim: '>=2.6.1+6'
  collection: ">=1.18.0"
dev_dependencies:
  process_run: ">=1.2.1+1"
  test: ">=1.24.0"
  dev_build: ">=1.1.2"
  build_runner: ">=2.4.13"
  build_test: '>=0.10.2'
  build_web_compilers: ">=4.0.11"
  path: ">=1.9.0"
  sembast: ">=3.7.4+3"
dependency_overrides:
resolution: workspace
  # idb_shim:
  #  path: ../../tekartik/idb_shim.dart/idb_shim
