include: package:lints/recommended.yaml

analyzer:
  errors:
    implementation_imports: ignore
  language:
    strict-casts: true
    strict-inference: true
  exclude:
    - build/**

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - avoid_print
    - avoid_slow_async_io
    - cancel_subscriptions
    - directives_ordering
    - no_adjacent_strings_in_list
    - omit_local_variable_types
    - prefer_const_constructors
    - prefer_single_quotes
    - public_member_api_docs
    - sort_child_properties_last
    - test_types_in_equals
    - throw_in_finally
    - unawaited_futures
    - unnecessary_statements
